* Welcome to the best collection of emacs extensions ever

I'm collecting and customizing the perfect environment for python
developement, using the most beautiful emacs customization to obtain a
really modern and exciting (yet stable) way to edit text files.

In the package are included also a lot of other packages and
configurations, it's an upstart for clean emacs installations, these
configuration however are very similar to emacs-starter-kit and I
suggest you to give it a try, emacs-for-python is designed to work
with it (instruction below).

** Features 
The package is splitted in various files, in this way it's very easy
to include what you really need.

*** Python Related

    - Ropemacs (Custom) : A refactoring library
    - Auto Completion with rope (Custom) : Tested to work well with Rope
    - Flymake + pyflakes (Custom): Highlight errors on the fly, improved
      from the standard version
    - Virtualenv : Original, In-development tool for using virtualenv in
      emacs.
    - Custom Yasnippet Snippets
    - Cython Mode: a mode for highlighting cython files

*** Editing Packages
    
    - Open Next Line: C-o will open a line under the cursor (very
      similar to vim o)
    - Auto Completion: Wonderful package for auto complete anything in
      emacs
    - Yasnippet: Snippets on steroids
    - Parentheses pairing (Custom): Bug-free parentheses pairing using
      skeletons.
    - smart-operator: Automatically adds spaces around arithmetic operators.

*** Configurations

    - ido activation
    - ibuffer instead of buffer menu
    - eshell configuration

*** Keybindings

    - Copy-Cut-Paste from clipboard with Super-C Super-X Super-V    
    - Calc Mode remapping to M-c
    - M-Tab remapped to C-Tab to avoid collisions with the desktop
      manager

** Installation

Put the emacs-for-python directory in .emacs.d directory), the add this line in your .emacs

: (load-file "/path/to/emacs-for-python/epy-init.el")

For further information and usage suggestions check http://wiki.github.com/gabrielelanaro/emacs-for-python/workflow

** Installation with emacs-starter-kit
** License

This is mostly a distribution with some little tweaks, with respect of
the licenses, my tweaks are distributed according to the term of the
GNU GPL license, described in the file COPYING.

Generally each file has its own license and copyright notice (most, if
not all of packages are GPL), the license of rope (GPL) is in
rope-dist/COPYING.
