(require 'cl)
(defun test-on-path ()
  (virtualenv-activate "~/.virtualenvs/pyusecase")
  (setq path (getenv "PATH"))
  (virtualenv-deactivate)
  (setq path-res (getenv "PATH"))
  (assert (not (eq path path-res)))
  )

(defun test-activating ()
  (virtualenv-activate "~/.virtualenvs/pyusecase")
  (shell-command "python -c 'import usecase'")
  (virtualenv-deactivate)
  )

(defun test-exec-path ()
  (virtualenv-activate "~/.virtualenvs/pyusecase")
  (setq myex exec-path)
  (virtualenv-deactivate)
  (setq myexne exec-path)
  (assert (not (eq myex myexne)))
  )

(test-on-path)
(test-activating)
(test-exec-path)