@include macros.texi
@ifset rawfile
@paragraphindent none
This is the README file for the AUCTeX distribution.

@quotation
Copyright (C) 2008 Free Software Foundation, Inc.

Copying and distribution of this file, with or without modification, are
permitted in any medium without royalty provided the copyright notice
and this notice are preserved.
@end quotation

@chapheading Introduction to @AUCTeX{}
@end ifset

@ifclear rawfile
@node Summary
@chapter Overview of @AUCTeX{}
@end ifclear

@ifset rawfile
This file gives a brief overview of what @AUCTeX{} is.  It is
@strong{not} an attempt to document @AUCTeX{}.  Real documentation for
@AUCTeX{} is available in the manual, which should be available as an
info file after installation.
@end ifset

@AUCTeX{} is a comprehensive customizable integrated environment for
writing input files for @TeX{}, @LaTeX{}, @ConTeXt{}, Texinfo, and
doc@TeX{} using Emacs or XEmacs.

It supports you in the insertion of macros, environments, and sectioning
commands by providing completion alternatives and prompting for
parameters.  It automatically indents your text as you type it and lets
you format a whole file at once.  The outlining and folding facilities
provide you with a focused and clean view of your text.

@AUCTeX{} lets you process your source files by running @TeX{} and
related tools (such as output filters, post processors for generating
indices and bibliographies, and viewers) from inside Emacs.  @AUCTeX{}
lets you browse through the errors @TeX{} reported, while it moves the
cursor directly to the reported error, and displays some documentation
for that particular error.  This will even work when the document is
spread over several files.

One component of @AUCTeX{} that @LaTeX{} users will find attractive is
@previewlatex{}, a combination of folding and in-source previewing
that provides true ``What You See Is What You Get'' experience in your
sourcebuffer, while letting you retain full control.
@ifset rawfile
For more information, see further below.
@end ifset

More detailed information about the features and usage of @AUCTeX{} can
be found in the
@ifset rawfile
@AUCTeX{} manual.  You can access it from within Emacs by typing
@kbd{C-h i d m auctex @key{RET}}.  If you prefer the standalone info
reader, issue the command @code{info auctex} in a terminal.
@end ifset
@ifclear rawfile
remainder of this manual.
@end ifclear

@AUCTeX{} is written entirely in Emacs Lisp, and hence you can easily
add new features for your own needs.  It is a GNU project and
distributed under the `GNU General Public License Version 3'.

The most recent version is always available at
@url{http://ftp.gnu.org/pub/gnu/auctex/}.

WWW users may want to check out the @AUCTeX{} page at
@url{http://www.gnu.org/software/auctex/}.

For comprehensive information about how to install @AUCTeX{}
@ifset rawfile
read the file @file{INSTALL} or @file{INSTALL.windows}, respectively.
@end ifset
@ifclear rawfile
@xref{Installation}, or @ref{Installation under MS Windows},
respectively.
@end ifclear

If you are considering upgrading @AUCTeX{}, the recent changes are
described in
@ifset rawfile
the @file{CHANGES} file.
@end ifset
@ifclear rawfile
@ref{Changes}.
@end ifclear

If you want to discuss @AUCTeX{} with other users or its developers,
there are several mailing lists you can use.

Send a mail with the subject ``subscribe'' to
@email{auctex-request@@gnu.org} in order to join the general discussion
list for @AUCTeX{}.  Articles should be sent to @email{auctex@@gnu.org}.
In a similar way, you can subscribe to the @email{info-auctex@@gnu.org}
list for just getting important announcements about @AUCTeX{}.  The list
@email{bug-auctex@@gnu.org} is for bug reports which you should usually
file with the @kbd{M-x TeX-submit-bug-report @key{RET}} command.  If you
want to address the developers of @AUCTeX{} themselves with technical
issues, they can be found on the discussion list
@email{auctex-devel@@gnu.org}.
